compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableProgressBars: false

logFilters:
  # Discard any "cannot be found in cache" messages
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs
