name: Release to stage
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:20-buster'
      install_packages_command: 'yarn install'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'packages/apps/build'
      s3_bucket_name: 'explorer.stage.cere.network'
      aws_account_id: ${{ vars.STG_NETWORK_AWS_ACCOUNT_ID }}
