name: Release to stage
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-cloudflare-pages.yaml@master
    with:
      project_name: 'cere-explorer-stage'
      build_container: 'node:20-buster'
      install_packages_command: 'yarn install'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'packages/apps/build'
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
